# Generated by Django 3.1.5 on 2021-04-27 12:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Игра')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Название новости')),
                ('text', models.TextField(verbose_name='Содержание')),
                ('image_list', models.ImageField(upload_to='news_images/list', verbose_name='Изображение')),
                ('image_news', models.ImageField(upload_to='news_images/news', verbose_name='Изображение')),
                ('publish_date', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('publish_time', models.TimeField(default='15:16', verbose_name='Время публикации')),
                ('delay_publication', models.DateTimeField(blank=True, null=True, verbose_name='Когда опубликовать')),
                ('slug', models.SlugField(unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Черновик')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_author', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True, verbose_name='Название')),
                ('tag', models.CharField(max_length=16, unique=True, verbose_name='Тег')),
                ('logo', models.ImageField(null=True, upload_to='teams_logo/', verbose_name='Лого')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='AddNews',
            fields=[
                ('news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.news')),
            ],
            bases=('news.news', django.views.generic.base.View),
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название турнира')),
                ('description', models.TextField(verbose_name='Описание турнира')),
                ('prize', models.TextField(verbose_name='Призовой')),
                ('image', models.ImageField(default='tournament.jpg', upload_to='', verbose_name='Лого турнира')),
                ('max_teams', models.PositiveSmallIntegerField(default=0, verbose_name='Максимальное количество команд')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('start_registration_date', models.DateField(verbose_name='Начало регистрации')),
                ('end_registration_date', models.DateField(verbose_name='Конец регистрации')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('status', models.BooleanField(default=False, verbose_name='Статус активности')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.game', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournaments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.tournaments')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, null=True, unique=True, verbose_name='Никнейм')),
                ('age', models.DecimalField(decimal_places=0, max_digits=2)),
                ('about', models.TextField(max_length=1000, verbose_name='О себе')),
                ('avatar', models.ImageField(upload_to='media/user_avatars', verbose_name='Аватар')),
                ('city', models.CharField(blank=True, max_length=25, null=True, verbose_name='Город')),
                ('university', models.CharField(blank=True, max_length=100, null=True, verbose_name='Университет')),
                ('group', models.CharField(blank=True, max_length=50, null=True, verbose_name='Учебная группа')),
                ('course', models.DecimalField(decimal_places=0, max_digits=1, verbose_name='Курс обучения')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.role', verbose_name='роль')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.team', verbose_name='команда')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Код вступления')),
                ('team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.team')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='Сообщение')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата публикации')),
                ('time', models.TimeField(default='15:16', verbose_name='Время публикации')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news', verbose_name='новость')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.comments', verbose_name='Родитель')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
