# Generated by Django 3.1.5 on 2021-05-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210429_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, to='news.Team'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='20:31', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='20:31', verbose_name='Время публикации'),
        ),
    ]
