# Generated by Django 3.1.5 on 2021-05-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210501_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team',
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='20:32', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='20:32', verbose_name='Время публикации'),
        ),
    ]
