# Generated by Django 3.1.5 on 2021-05-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210501_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.ImageField(null=True, upload_to='icon_game/', verbose_name='Иконка игры'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='20:45', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='20:45', verbose_name='Время публикации'),
        ),
    ]
