# Generated by Django 3.1.5 on 2021-05-02 15:49

from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20210502_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTournament',
            fields=[
                ('tournaments_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='news.tournaments')),
            ],
            bases=('news.tournaments', django.views.generic.base.View),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='18:49', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='18:49', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default/player-no-avatar.png', upload_to='media/user_avatars', verbose_name='Аватар'),
        ),
    ]
