# Generated by Django 3.1.5 on 2021-05-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20210502_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='20:26', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='20:26', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата начала'),
        ),
    ]
