# Generated by Django 3.1.5 on 2021-05-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20210505_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='12:45', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='12:45', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Лого турнира'),
        ),
    ]
