# Generated by Django 3.1.5 on 2021-05-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20210506_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='image',
            field=models.ImageField(upload_to='media/tournaments/', verbose_name='Лого турнира'),
        ),
    ]
