# Generated by Django 3.1.5 on 2021-05-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0021_auto_20210506_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='14:28', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='14:28', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Лого турнира'),
        ),
    ]
