# Generated by Django 3.1.5 on 2021-09-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20210514_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournaments',
            name='count_registration_teams',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество зарегестрированных команд'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='19:55', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='19:55', verbose_name='Время публикации'),
        ),
    ]
