# Generated by Django 3.1.5 on 2021-09-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0026_auto_20210917_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentregistration',
            options={'verbose_name': 'Турнир рег', 'verbose_name_plural': 'Турниры рег'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='20:15', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='20:15', verbose_name='Время публикации'),
        ),
    ]
