# Generated by Django 3.1.5 on 2021-09-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0029_auto_20210917_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='22:28', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='22:28', verbose_name='Время публикации'),
        ),
    ]
