# Generated by Django 3.1.5 on 2021-09-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0030_auto_20210917_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ManyToManyField(blank=True, null=True, to='news.Tournaments', verbose_name='Турниры'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='22:45', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='22:45', verbose_name='Время публикации'),
        ),
    ]
