# Generated by Django 3.1.5 on 2021-09-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_auto_20210917_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='23:29', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='23:29', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='team',
            name='tournament',
            field=models.ManyToManyField(blank=True, to='news.Tournaments', verbose_name='Турниры'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='teams',
            field=models.ManyToManyField(blank=True, to='news.Team', verbose_name='Команда'),
        ),
    ]
