# Generated by Django 3.1.5 on 2021-09-17 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0032_auto_20210917_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentregistration',
            name='teams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.team'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='23:54', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='23:54', verbose_name='Время публикации'),
        ),
    ]
