# Generated by Django 3.1.5 on 2021-09-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0033_auto_20210917_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='19:35', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='19:35', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='tournaments',
            name='count_registration_teams',
            field=models.IntegerField(default=0, verbose_name='Количество зарегестрированных команд'),
        ),
    ]
