# Generated by Django 4.1.3 on 2022-11-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_auto_20210918_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.TimeField(default='21:47', verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.TimeField(default='21:47', verbose_name='Время публикации'),
        ),
    ]
