# Generated by Django 4.1.3 on 2022-11-16 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=75, verbose_name='IP')),
                ('server_username', models.CharField(max_length=75, verbose_name='Username')),
                ('secret', models.CharField(max_length=75, verbose_name='Password')),
                ('port', models.IntegerField(verbose_name='Порт')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сервер',
                'verbose_name_plural': 'Серверы',
            },
        ),
        migrations.CreateModel(
            name='AddServer',
            fields=[
                ('server_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='csservers.server')),
            ],
            bases=('csservers.server', django.views.generic.base.View),
        ),
        migrations.CreateModel(
            name='StartServer',
            fields=[
                ('server_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='csservers.server')),
            ],
            bases=('csservers.server', django.views.generic.base.View),
        ),
    ]
